var customerRecordId;

function pageInit() {
	customerRecordId = nlapiGetFieldValue("custpage_id");

	var cust_rec = nlapiLoadRecord("customer", customerRecordId);

	nlapiSetFieldValue(
		"industry",
		cust_rec.getFieldValue("custentity_industry_category")
	);
	nlapiSetFieldValue("franchisee", cust_rec.getFieldValue("partner"));
}

function saveRecord() {
	var salesRepId = nlapiGetUser();

	if (isNullorEmpty(nlapiGetFieldValue("campaign_type"))) {
		alert("Please Enter Value for Campaign");
		return false;
	}

	var old_sales_record_id = nlapiGetFieldValue("sales_record_id");

	var customer_rec = nlapiLoadRecord("customer", customerRecordId);

	customer_status = customer_rec.getFieldValue("entitystatus");
	lead_source = customer_rec.getFieldValue("leadsource");
	var partner = customer_rec.getFieldValue("partner");
	if (nlapiGetFieldValue("franchisee") == 435) {
		alert("Please Select a Franchisee");
		return false;
	}

	var oldCampaign = null;
	var newSalesRecordId = null;

	if (!isNullorEmpty(old_sales_record_id)) {
		var old_sales_record = nlapiLoadRecord(
			"customrecord_sales",
			old_sales_record_id
		);
		oldCampaign = old_sales_record.getFieldValue("custrecord_sales_campaign");
		if (oldCampaign == 87) {
			old_sales_record.setFieldValue(
				"custrecord_sales_assigned",
				nlapiGetFieldValue("sales_rep")
			);
			newSalesRecordId = nlapiSubmitRecord(old_sales_record);
		} else {
			old_sales_record.setFieldValue("custrecord_sales_deactivated", "T");
			old_sales_record.setFieldValue("custrecord_sales_completed", "T");
			nlapiSubmitRecord(old_sales_record);
		}

		if (customer_status != 13) {
			// customer_rec.setFieldValue('entitystatus', 60);
			// customer_rec.setFieldValue('custentity_date_suspect_reassign', getDate());
		}
	} else {
		if (customer_status != 22 && customer_status != 13) {
			//If the leads generated by the franchisee has incompleted data and Aleyna assigns to Liam, change staus to SUSPECT - UNQUALIFIED
			if (
				salesRepId == 1623053 &&
				nlapiGetFieldValue("sales_rep") == 1809382 &&
				lead_source == -4
			) {
				customer_rec.setFieldValue("entitystatus", 38); //SUSPECT - UNQUALIFIED
			}
			//Once the franchisee genearted leds have been qualified by Liam and he assigns to another rep, change status to SUSPECT - QUALIFIED
			if (salesRepId == 1809382 && customer_status == 38 && lead_source == -4) {
				customer_rec.setFieldValue("entitystatus", 42); //SUSPECT - QUALIFIED
			}
		}
	}

	customer_rec.setFieldValue(
		"custentity_industry_category",
		nlapiGetFieldValue("industry")
	);
	customer_rec.setFieldValue("custentity13", null);
	customer_rec.setFieldValue("partner", nlapiGetFieldValue("franchisee"));

	nlapiSubmitRecord(customer_rec);

	if (oldCampaign == null || oldCampaign != 87) {
		var recordtoCreate = nlapiCreateRecord("customrecord_sales");
		var date2 = new Date();
		var subject = "";
		var body = "";

		var userRole = parseInt(nlapiGetContext().getRole());

		// Set customer, campaign, user, last outcome, callback date
		recordtoCreate.setFieldValue("custrecord_sales_customer", customerRecordId);
		recordtoCreate.setFieldValue(
			"custrecord_sales_campaign",
			nlapiGetFieldValue("campaign_type")
		);
		// if(userRole == 1005){
		//     // alert(123);
		//     recordtoCreate.setFieldValue('custrecord_sales_assigned', nlapiGetUser());
		//     nlapiSetFieldValue('salesrep', nlapiGetUser());
		// } else {
		// alert(333);
		recordtoCreate.setFieldValue(
			"custrecord_sales_assigned",
			nlapiGetFieldValue("sales_rep")
		);
		nlapiSetFieldValue("salesrep", nlapiGetFieldValue("sales_rep"));
		// }
		// alert(nlapiGetUser());
		recordtoCreate.setFieldValue("custrecord_sales_outcome", 20);
		recordtoCreate.setFieldValue("custrecord_sales_callbackdate", getDate());
		recordtoCreate.setFieldValue(
			"custrecord_sales_callbacktime",
			nlapiDateToString(date2.addHours(0), "timeofday")
		);
		if (nlapiGetFieldValue("campaign_type") == 56) {
			recordtoCreate.setFieldValue("custrecord_sales_followup_stage", 5);
		}

		newSalesRecordId = nlapiSubmitRecord(recordtoCreate);
	}

	nlapiSetFieldValue("sales_record_id", newSalesRecordId);

	return true;
}

function getDate() {
	var date = new Date();
	// if (date.getHours() > 6) {
	//     date = nlapiAddDays(date, 1);
	// }
	date = nlapiDateToString(date);

	return date;
}

Date.prototype.addHours = function (h) {
	this.setHours(this.getHours() + h);
	return this;
};
